### ISSUE TITLE
Latest release fails with Markdown 3.4

### ISSUE THREAD

**Issue by oprypin** [Python-Markdown/github-links#10]
Cause: https://github.com/Python-Markdown/markdown/commit/a767b2daaad78ba32d45a4f1dabb7c5e218f030a

Error: `ImportError: cannot import name 'etree' from 'markdown.util'`

I see that there's an old commit fixing this but it's not included in any release.
https://github.com/Python-Markdown/github-links/commit/7b3a23cea0df503d7832e7480d8e46511bd27bf7

**Comment by oprypin** [comment]
Thanks

**Comment by waylan** [comment]
Thanks for bringing this to my attention.
